# Generated by Django 5.1.3 on 2024-11-26 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('name', models.CharField(max_length=550)),
                ('desp', models.TextField()),
                ('orgianal_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
