# Generated by Django 5.1.3 on 2024-11-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='watch.png', upload_to='product_images/'),
        ),
    ]
