# Generated by Django 5.1.3 on 2024-11-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default='watch.png', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='watch.png', upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='products',
            name='image4',
            field=models.ImageField(default='watch.png', upload_to='product_images/'),
        ),
    ]
