# Generated by Django 5.1.3 on 2024-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_products_image3_alter_products_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=models.ImageField(default='watch.png', height_field=300, upload_to='product_images/', width_field=300),
        ),
    ]
