# Generated by Django 5.1.3 on 2024-11-29 14:52

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_order_price_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, default='watch.png', force_format=None, keep_meta=True, quality=85, scale=None, size=[600, 600], upload_to='product_images/'),
        ),
    ]
